version: "2"
services:
  drug_scraper_puppeteer:
    container_name: drug_scraper_puppeteer-local
    build:
      context: ./docker/puppeteer
    volumes:
      - ./:/var/www/
    working_dir: /var/www/
    depends_on:
      - mysql
    links:
      - mysql
    tty: true
    expose:
      - 3000
    ports:
      - 3333:3000
    command: node express_app/server.js


  drug_scraper_puppeteer_2:
      container_name: drug_scraper_puppeteer-local-2
      build:
        context: ./docker/puppeteer
      volumes:
        - ./:/var/www/
      working_dir: /var/www/
      depends_on:
        - mysql
      links:
        - mysql
      tty: true
      expose:
        - 3000
      command: node express_app/server.js

#  drug_scraper_puppeteer_3:
#      container_name: drug_scraper_puppeteer-local-3
#      build:
#        context: ./docker/puppeteer
#      volumes:
#        - ./:/var/www/
#      working_dir: /var/www/
#      depends_on:
#        - mysql
#      links:
#        - mysql
#      tty: true
#      expose:
#        - 3000
#      command: node express_app/server.js
#
#  drug_scraper_puppeteer_4:
#      container_name: drug_scraper_puppeteer-local-4
#      build:
#        context: ./docker/puppeteer
#      volumes:
#        - ./:/var/www/
#      working_dir: /var/www/
#      depends_on:
#        - mysql
#      links:
#        - mysql
#      tty: true
#      expose:
#        - 3000
#      command: node express_app/server.js
#
#  drug_scraper_puppeteer_5:
#      container_name: drug_scraper_puppeteer-local-5
#      build:
#        context: ./docker/puppeteer
#      volumes:
#        - ./:/var/www/
#      working_dir: /var/www/
#      depends_on:
#        - mysql
#      links:
#        - mysql
#      tty: true
#      expose:
#        - 3000
#      command: node express_app/server.js
#
#  drug_scraper_puppeteer_6:
#      container_name: drug_scraper_puppeteer-local-6
#      build:
#        context: ./docker/puppeteer
#      volumes:
#        - ./:/var/www/
#      working_dir: /var/www/
#      depends_on:
#        - mysql
#      links:
#        - mysql
#      tty: true
#      expose:
#        - 3000
#      command: node express_app/server.js
#
#  drug_scraper_puppeteer_7:
#      container_name: drug_scraper_puppeteer-local-7
#      build:
#        context: ./docker/puppeteer
#      volumes:
#        - ./:/var/www/
#      working_dir: /var/www/
#      depends_on:
#        - mysql
#      links:
#        - mysql
#      tty: true
#      expose:
#        - 3000
#      command: node express_app/server.js
#
#  drug_scraper_puppeteer_8:
#      container_name: drug_scraper_puppeteer-local-8
#      build:
#        context: ./docker/puppeteer
#      volumes:
#        - ./:/var/www/
#      working_dir: /var/www/
#      depends_on:
#        - mysql
#      links:
#        - mysql
#      tty: true
#      expose:
#        - 3000
#      command: node express_app/server.js
#
#  drug_scraper_puppeteer_9:
#      container_name: drug_scraper_puppeteer-local-9
#      build:
#        context: ./docker/puppeteer
#      volumes:
#        - ./:/var/www/
#      working_dir: /var/www/
#      depends_on:
#        - mysql
#      links:
#        - mysql
#      tty: true
#      expose:
#        - 3000
#      command: node express_app/server.js
#
#  drug_scraper_puppeteer_10:
#      container_name: drug_scraper_puppeteer-local-10
#      build:
#        context: ./docker/puppeteer
#      volumes:
#        - ./:/var/www/
#      working_dir: /var/www/
#      depends_on:
#        - mysql
#      links:
#        - mysql
#      tty: true
#      expose:
#        - 3000
#      command: node express_app/server.js

#  drug_scraper_node:
#    container_name: drug_scraper_node-local
#    build:
#      context: ./docker/node
#    volumes:
#      - ./:/var/www/html/drug_scraper
#    working_dir: /var/www/html/drug_scraper
#    depends_on:
#      - mysql
#    links:
#      - mysql
#    tty: true
#    ports:
#      - "8888:8080"

  ###############################################################################
  # Drug Scraper: PHP App
  ###############################################################################
  drug_scraper:
    container_name: drug_scraper_laravel-local
    build:
      context: .
      dockerfile: DockerfileLocal
    volumes:
      - ./:/var/www/html/drug_scraper
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - "8989:8000"

#    expose:
#      - 9515

  ###############################################################################
  # Drug Scraper: MySql
  ###############################################################################
  mysql:
    container_name: drug_scraper_mysql-local
    image: mysql:5.6
    user: "mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=scraper
    ports:
      - "3307:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/blink_pricing.sql:/docker-entrypoint-initdb.d/blink_pricing.sql
      - ./docker/mysql/drug_pull_blink.sql:/docker-entrypoint-initdb.d/drug_pull_blink.sql
      - ./docker/mysql/drug_pull_goodrx.sql:/docker-entrypoint-initdb.d/drug_pull_goodrx.sql
      - ./docker/mysql/drug_pull_singlecare.sql:/docker-entrypoint-initdb.d/drug_pull_singlecare.sql
      - ./docker/mysql/drug_pull_unarx.sql:/docker-entrypoint-initdb.d/drug_pull_unarx.sql
      - ./docker/mysql/drug_pull_wellrx.sql:/docker-entrypoint-initdb.d/drug_pull_wellrx.sql
      - ./docker/mysql/goodrx_mar_08.sql:/docker-entrypoint-initdb.d/goodrx_mar_08.sql
      - ./docker/mysql/singlecare_staging.sql:/docker-entrypoint-initdb.d/singlecare_staging.sql
      - ./docker/mysql/unarx_staging.sql:/docker-entrypoint-initdb.d/unarx_staging.sql
      - ./docker/mysql/wellrx_api_staging.sql:/docker-entrypoint-initdb.d/wellrx_api_staging.sql